title: Gathering.AI
email: lhkhiem28@gmail.com
description: >- 
  To write

plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
minimal_mistakes_skin_2: default
markdown: kramdown
permalink: /:categories/:title/
paginate_path: /page:num/
paginate: 8
include: 
  - _pages

search: true
author: 
  name   : "Gathering.AI"
  avatar : "/assets/images/seedling.png"
  bio    : "Gather knowledge on various AI topics"
  links: 
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/lhkhiem28"
    - label: "Google Scholar"
      icon: "fa-regular fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=vi&user=T8I-cLIAAAAJ&view_op=list_works&sortby=pubdate"

footer:
  links:
    - label: "Email"
      icon: "fa-regular fa-envelope"
      url: "mailto:lhkhiem28@gmail.com"

category_archive: 
  type: liquid
  path: /categories/
tag_archive: 
  type: liquid
  path: /tags/
year_archive: 
  type: liquid
  path: /posts/

defaults: 
  - scope: 
      path: "_pages"
      type: pages
    values: 
      layout: single
      author_profile: true
  - scope: 
      path: ""
      type: posts
    values: 
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: true
      related: false

repository: gather-ai/gather-ai.github.io
comments: 
  provider: "utterances"
  utterances: 
    theme: "github-dark"
    issue_term: "pathname"