title: Gathering.AI
email: lhkhiem28@gmail.com
description: >- 
  To write

plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
markdown: kramdown
permalink: /:categories/:title/
paginate_path: /page:num/
paginate: 8
include: 
  - _pages
header: 
  image: "/assets/images/rome.jpg"

search: true
author: 
  name   : "Welcome to Gathering.AI"
  avatar : "/assets/images/seedling.png"
  bio    : "Gather knowledge of various AI topics. "
  links: 
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lhkhiem28"
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?hl=vi&user=T8I-cLIAAAAJ&view_op=list_works&sortby=pubdate"

category_archive: 
  type: liquid
  path: /categories/
tag_archive: 
  type: liquid
  path: /tags/
year_archive: 
  type: liquid
  path: /posts/

repository: gather-ai/gather-ai.github.io
comments: 
  provider: "utterances"
  utterances: 
    theme: "github-dark"
    issue_term: "pathname"

defaults: 
  # _posts
  - scope: 
      path: ""
      type: posts
    values: 
      layout: single
      author_profile: true

      read_time: true
      share: true
      comments: true
      related: true

  # _pages
  - scope: 
      path: "_pages"
      type: pages
    values: 
      layout: single
      author_profile: true